### ISSUE TITLE
Stemmed output is always lowercase

### ISSUE THREAD

**Issue by zesch** [LeonieWeissweiler/CISTEM#1]
Even in case-sensitive mode, the output is always lower case.
Is that on purpose?

**Comment by LeonieWeissweiler** [comment]
Yes it is, the point of the case-insensitive version is that if casing in a corpus might be incorrectly upper case, the stemmer would normally not strip "t". In that case, slightly better performance is achieved by always stripping "t", which is what the case-insensitive version is for. Both this version and the normal case-sensitive version convert the word to lowercase.
