### ISSUE TITLE
Removing of prefix "ge" is too aggressive

### ISSUE THREAD

**Issue by a-kempka** [LeonieWeissweiler/CISTEM#7]
Thank you for the useful stemmer. I have stumbled upon an issue:
There should be some exceptions for removing the prefix "ge". 
E.g. 
"Geschlecht" is stemmed to "schlecht"
"Gesellschaft" is stemmed to "sellschaft"
"gesamt" is stemmed to "samt"
"genau" is stemmed to "nau"
etc.

**Comment by janfri** [comment]
"Geschlecht" is stemmed to "schlecht", this is bad. SCNR

**Comment by wollmers** [comment]
Work around would be an option to switch it on or off.

**Comment by LeonieWeissweiler** [comment]
Hi, please see the paper https://link.springer.com/content/pdf/10.1007/978-3-319-73706-5_8.pdf for insight on how we constructed the stemming algorithm. In short, there are some cases in which removing "ge" is too much, but overall, it is best to do it. As the unique advantage of a stemmer is that it is fast, I will not be adding specific exceptions, but you should be able to add some yourself that are relevant to your application scenario.
