### ISSUE TITLE
Methods stem and segments should return the same stem

### ISSUE THREAD

**Issue by wollmers** [LeonieWeissweiler/CISTEM#8]
The difference of transformation between `stem()` and `segments()` is:

- removement of prefix ge-
- transformation of äöü to aou
- transformation of ß to ss

Example:

```
#!perl
use strict;
use warnings;
use utf8;

binmode(STDOUT,":encoding(UTF-8)");
binmode(STDERR,":encoding(UTF-8)");

use lib qw(../CISTEM);

use Cistem;

my @words = qw/geheilwässert/;

for my $word (@words) {
  for my $case_sensitive (0..1) {
    print 'Cistem::stem(',$word,',',$case_sensitive,'): ',
    Cistem::stem($word,$case_sensitive),"\n";
  }

  for my $case_sensitive (0..1) {
    print 'Cistem::segment(',$word,',',$case_sensitive,'): ',
    join('-',Cistem::segment($word,$case_sensitive)),"\n";
  }
}
```
Which results in:

```
~/github/perl/CISTEM-test$ perl cistem.t
Cistem::stem(geheilwässert,0): heilwass
Cistem::stem(geheilwässert,1): heilwass
Cistem::segment(geheilwässert,0): geheilwäss-ert
Cistem::segment(geheilwässert,1): geheilwäss-ert
```
I would expect the same segmentation:

`ge-heilwass-ert`

This would also allow sharing most of the code.

**Comment by LeonieWeissweiler** [comment]
This is intentional. The transformations that you listed significantly increase stemmer performance, but it would not be logical to change the stem in a segmentation scenario, for example if the application requires rejoining the segments.
